/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[AGENTS]
(
[AGENT_CODE] [varchar] (6) NOT NULL,
[AGENT_NAME] [varchar] (40) NULL,
[WORKING_AREA] [varchar] (35) NULL,
[COMMISSION] [decimal] (10, 2) NULL,
[PHONE_NO] [varchar] (15) NULL,
[COUNTRY] [varchar] (25) NULL
)
GO
ALTER TABLE [dbo].[AGENTS] ADD CONSTRAINT [PK__AGENTS__843A8BBA695E5C0A] PRIMARY KEY CLUSTERED  ([AGENT_CODE])
GO
