/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[CUSTOMER]
(
[CUST_CODE] [varchar] (6) NOT NULL,
[CUST_NAME] [varchar] (40) NOT NULL,
[CUST_CITY] [varchar] (35) NULL,
[WORKING_AREA] [varchar] (35) NOT NULL,
[CUST_COUNTRY] [varchar] (20) NOT NULL,
[GRADE] [int] NULL,
[OPENING_AMT] [decimal] (12, 2) NOT NULL,
[RECEIVE_AMT] [decimal] (12, 2) NOT NULL,
[PAYMENT_AMT] [decimal] (12, 2) NOT NULL,
[OUTSTANDING_AMT] [decimal] (12, 2) NOT NULL,
[PHONE_NO] [varchar] (17) NOT NULL,
[AGENT_CODE] [varchar] (6) NOT NULL
)
GO
ALTER TABLE [dbo].[CUSTOMER] ADD CONSTRAINT [PK__CUSTOMER__8393C4A18033BC87] PRIMARY KEY CLUSTERED  ([CUST_CODE])
GO
ALTER TABLE [dbo].[CUSTOMER] ADD CONSTRAINT [FK_CUSTOMER_AGENT] FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[AGENTS] ([AGENT_CODE])
GO
ALTER TABLE [dbo].[CUSTOMER] ADD CONSTRAINT [FK__CUSTOMER__AGENT___38996AB5] FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[AGENTS] ([AGENT_CODE])
GO
