/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ORDERS]
(
[ORD_NUM] [decimal] (6, 0) NOT NULL,
[ORD_AMOUNT] [decimal] (12, 2) NOT NULL,
[ADVANCE_AMOUNT] [decimal] (12, 2) NOT NULL,
[ORD_DATE] [date] NOT NULL,
[CUST_CODE] [varchar] (6) NOT NULL,
[AGENT_CODE] [varchar] (6) NOT NULL,
[ORD_DESCRIPTION] [varchar] (60) NOT NULL
)
GO
ALTER TABLE [dbo].[ORDERS] ADD CONSTRAINT [PK__ORDERS__27AB607C77FFF8BC] PRIMARY KEY CLUSTERED  ([ORD_NUM])
GO
ALTER TABLE [dbo].[ORDERS] ADD CONSTRAINT [FK_ORDERS_AGENT] FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[AGENTS] ([AGENT_CODE])
GO
ALTER TABLE [dbo].[ORDERS] ADD CONSTRAINT [FK_ORDERS_CUSTOMER] FOREIGN KEY ([CUST_CODE]) REFERENCES [dbo].[CUSTOMER] ([CUST_CODE])
GO
